# Generated by Django 4.2.4 on 2023-12-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_advocate_comapny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='comapny',
            new_name='company',
        ),
    ]
